In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
a = np.array([23, 21, 19, 24, 35, 17, 18, 24, 33, 27, 21, 23])
b = np.array([31, 28, 19, 24, 32, 27, 16, 41, 23, 32, 29, 31])

In [3]:
a.mean()

np.float64(23.75)

In [4]:
b.mean()

np.float64(27.75)

In [5]:
d = b.mean() - a.mean()
d

np.float64(4.0)

In [6]:
np.ones(len(b))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
sum1 = np.append(np.zeros(len(a)), np.ones(len(b)))

In [8]:
sum2 = np.append(a, b)

In [9]:
sales = np.array([sum1, sum2])

In [10]:
print(sales)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.]
 [23. 21. 19. 24. 35. 17. 18. 24. 33. 27. 21. 23. 31. 28. 19. 24. 32. 27.
  16. 41. 23. 32. 29. 31.]]


In [11]:
sales_t = sales.T
sales_t

array([[ 0., 23.],
       [ 0., 21.],
       [ 0., 19.],
       [ 0., 24.],
       [ 0., 35.],
       [ 0., 17.],
       [ 0., 18.],
       [ 0., 24.],
       [ 0., 33.],
       [ 0., 27.],
       [ 0., 21.],
       [ 0., 23.],
       [ 1., 31.],
       [ 1., 28.],
       [ 1., 19.],
       [ 1., 24.],
       [ 1., 32.],
       [ 1., 27.],
       [ 1., 16.],
       [ 1., 41.],
       [ 1., 23.],
       [ 1., 32.],
       [ 1., 29.],
       [ 1., 31.]])

In [12]:
np.random.shuffle(sales_t)
sales_t

array([[ 0., 21.],
       [ 0., 24.],
       [ 0., 24.],
       [ 1., 31.],
       [ 1., 41.],
       [ 1., 32.],
       [ 1., 24.],
       [ 0., 23.],
       [ 0., 18.],
       [ 1., 28.],
       [ 0., 17.],
       [ 0., 21.],
       [ 0., 27.],
       [ 0., 23.],
       [ 1., 32.],
       [ 1., 16.],
       [ 1., 23.],
       [ 0., 19.],
       [ 1., 19.],
       [ 0., 33.],
       [ 1., 31.],
       [ 0., 35.],
       [ 1., 29.],
       [ 1., 27.]])