In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
a = np.array([23, 21, 19, 24, 35, 17, 18, 24, 33, 27, 21, 23])
b = np.array([31, 28, 19, 24, 32, 27, 16, 41, 23, 32, 29, 31])

In [4]:
a.mean()

np.float64(23.75)

In [5]:
b.mean()

np.float64(27.75)

In [6]:
d = b.mean() - a.mean()
d

np.float64(4.0)

In [7]:
np.ones(len(b))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
sum1 = np.append(np.zeros(len(a)), np.ones(len(b)))

In [9]:
sum2 = np.append(a, b)

In [10]:
sales = np.array([sum1, sum2])

In [11]:
print(sales)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.]
 [23. 21. 19. 24. 35. 17. 18. 24. 33. 27. 21. 23. 31. 28. 19. 24. 32. 27.
  16. 41. 23. 32. 29. 31.]]


In [12]:
sales_t = sales.T
sales_t

array([[ 0., 23.],
       [ 0., 21.],
       [ 0., 19.],
       [ 0., 24.],
       [ 0., 35.],
       [ 0., 17.],
       [ 0., 18.],
       [ 0., 24.],
       [ 0., 33.],
       [ 0., 27.],
       [ 0., 21.],
       [ 0., 23.],
       [ 1., 31.],
       [ 1., 28.],
       [ 1., 19.],
       [ 1., 24.],
       [ 1., 32.],
       [ 1., 27.],
       [ 1., 16.],
       [ 1., 41.],
       [ 1., 23.],
       [ 1., 32.],
       [ 1., 29.],
       [ 1., 31.]])

In [13]:
np.random.shuffle(sales_t)
sales_t

array([[ 0., 33.],
       [ 0., 35.],
       [ 1., 32.],
       [ 1., 19.],
       [ 1., 29.],
       [ 1., 31.],
       [ 0., 21.],
       [ 1., 23.],
       [ 1., 27.],
       [ 1., 28.],
       [ 1., 32.],
       [ 0., 23.],
       [ 0., 17.],
       [ 0., 23.],
       [ 1., 31.],
       [ 0., 27.],
       [ 0., 21.],
       [ 1., 16.],
       [ 0., 24.],
       [ 0., 19.],
       [ 0., 18.],
       [ 1., 24.],
       [ 1., 41.],
       [ 0., 24.]])

In [14]:
experiment_label = np.random.randint(0, 2, len(sales_t))
experiment_label

array([1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1], dtype=int32)

In [18]:
print(len(experiment_label), len(sales_t[:, 1]))


2 24


In [27]:
experiment_data = np.array([experiment_label, sales_t[:, 1]], dtype=object)
experiment_data

array([array([[ 1.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,
                0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  1.],
              [33., 35., 32., 19., 29., 31., 21., 23., 27., 28., 32., 23., 17.,
               23., 31., 27., 21., 16., 24., 19., 18., 24., 41., 24.]])        ,
       array([33., 35., 32., 19., 29., 31., 21., 23., 27., 28., 32., 23., 17.,
              23., 31., 27., 21., 16., 24., 19., 18., 24., 41., 24.])         ],
      dtype=object)

In [24]:
experiment_data_t = experiment_data.T
experiment_data_t

array([array([[ 1.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,
                0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  1.],
              [33., 35., 32., 19., 29., 31., 21., 23., 27., 28., 32., 23., 17.,
               23., 31., 27., 21., 16., 24., 19., 18., 24., 41., 24.]])        ,
       array([33., 35., 32., 19., 29., 31., 21., 23., 27., 28., 32., 23., 17.,
              23., 31., 27., 21., 16., 24., 19., 18., 24., 41., 24.])         ],
      dtype=object)

In [28]:
experiment_data_t[experiment_data_t[:,0] == 1][:, 1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed